DROP TABLE IF EXISTS Documents;
CREATE TABLE IF NOT EXISTS Documents (UserId INTEGER PRIMARY KEY, TextData TEXT, Link TEXT URL);
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) UNIQUE NOT NULL,
    hashedpassword VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
